version: '3.4'

services:
  dockermultiprofiledemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - PASSWORD_ENV_SEEDED=some.long.password.fllkwefiwejf23049uwlekjf.sEFWEFGR98^&$
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      args:
        - BUILD_CONFIGURATION=Release
        - PASSWORD_ENV_SEEDED=${PASSWORD_ENV_SEEDED}