services:
  dockermultiprofiledemo.api:
    image: ${DOCKER_REGISTRY-}dockermultiprofiledemo.api
    build:
      context: .
      dockerfile: DockerMultiProfileDemo/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ISDOCKERENV=true
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - dockermultiprofiledemo.db

  dockermultiprofiledemo.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/dockermultiprofiledemo-db:/var/lib/postgresql/data