services:
  dockermultiprofiledemo.api:
    container_name: dockermultiprofiledemo.api.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    build:
      args:
        - BUILD_CONFIGURATION=Release
    networks:
      - proxy
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockermultiprofiledemo.rule=Host(`${DOMAIN_APP}`)
      - traefik.http.services.dockermultiprofiledemo.loadbalancer.server.port=8080

  dockermultiprofiledemo.db:
     container_name: dockermultiprofiledemo.db.release
     networks:
       - backend
  
  traefik:
    container_name: traefik
    image: traefik:v3.1.2
    ports:
      - 80:80
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true

networks:
  proxy:
    name: proxy
  backend:
    name: backend

volumes:
  # letsencrypt:
  #   name: letsencrypt
  database_data:
    name: database_data