services:
  dockermultiprofiledemo.api:
    container_name: dockermultiprofiledemo.api.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "8080:8080"

  dockermultiprofiledemo.db:
    container_name: dockermultiprofiledemo.db.dev
    ports:
      - "5432:5432" 
  
  dockermultiprofiledemo.cache:
    ports:
      - '6379:6379'

  pythonproject:
    ports:
      - "4949:4949"