// <auto-generated />
using DockerMultiProfileDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DockerMultiProfileDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824064025_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DockerMultiProfileDemo.Database.SomeEntityModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("someProp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("SomeEntityModels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            someProp = "First Entity"
                        },
                        new
                        {
                            id = 2,
                            someProp = "Second Entity"
                        },
                        new
                        {
                            id = 3,
                            someProp = "Third Entity"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
